package com.sdut.product.dao;

import com.sdut.product.pojo.User;
import com.sdut.product.pojo.UserRole;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.Set;

/**
 * @ClassName LoginMapper
 * @Discription
 * @Author yinyuchen
 * @Date 2019/3/20 10:32
 **/
@Mapper
public interface LoginMapper {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product..user
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    User selectByNameAndPwd(User user);

    int updatePassword(@Param(value = "username") String username, @Param(value = "password") String password);

    String selectByName(@Param(value = "username") String username);

    User findByName(@Param(value = "username") String username);

    String findUserIdByName(String username);

    Set<UserRole> findRoleIdByUid(String userId);

    String findRoleByRoleId(@Param(value = "roleId") String roleId);

    Set<String> findPermissionIdByRoleId(@Param(value = "roleId") String roleId);

    String findPermissionById(@Param(value = "permissionId") String permissionId);
}
