package com.sdut.product.pojo;

import com.sdut.product.exception.ErrorCodeEnum;
import io.swagger.annotations.ApiModelProperty;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product..user.id
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product..user.name
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    private String name;


    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product..user.avatar
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product..user.username
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product..user.password
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    private String password;

    private int pageNum = 1;

    private int pageSize = 20;

    public int getPageNum() {
        return pageNum;
    }

    public void setPageNum(int pageNum) {
        this.pageNum = pageNum;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.id
     *
     * @return the value of product..user.id
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.id
     *
     * @param id the value for product..user.id
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.name
     *
     * @return the value of product..user.name
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.name
     *
     * @param name the value for product..user.name
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.name
     *
     * @return the value of product..user.name
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.name
     *
     * @param sex the value for product..user.name
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.avatar
     *
     * @return the value of product..user.avatar
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.avatar
     *
     * @param avatar the value for product..user.avatar
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.username
     *
     * @return the value of product..user.username
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.username
     *
     * @param username the value for product..user.username
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product..user.password
     *
     * @return the value of product..user.password
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product..user.password
     *
     * @param password the value for product..user.password
     *
     * @mbggenerated Tue Mar 12 11:38:17 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }


    @ApiModelProperty("注册状态:<br>" +
            "1001-用户名或者密码错误!<br>" )
    private int registerStatus;
    @ApiModelProperty("注册状态:  相应描述")
    private String message;

    public User() {
    }

    public User(ErrorCodeEnum errorCodeEnum) {
        this.registerStatus = errorCodeEnum.getErrorCode();
        this.message = errorCodeEnum.getErrorMsg();
    }

    @Override
    public String toString() {
        return "User{" +
                "id='" + id + '\'' +
                ", name='" + name + '\'' +
                ", sex=" + sex +
                ", avatar='" + avatar + '\'' +
                ", username='" + username + '\'' +
                ", password='" + password + '\'' +
                ", pageNum=" + pageNum +
                ", pageSize=" + pageSize +
                ", registerStatus=" + registerStatus +
                ", message='" + message + '\'' +
                '}';
    }
}